const PRIMARY_COLOR = "#E64579";
const SECONDARY_COLOR = "#fabc60";
const WHITE = "#FFFFFF";
const LIGHT_GRAY = "#f1f1f1";
const GRAY = "#757E90";
const DARK_GRAY = "#363636";
const BLACK = "#000000";

const ONLINE_STATUS = "#46A575";
const OFFLINE_STATUS = "#D04949";

const STAR_ACTIONS = "#FFA200";
const LIKE_ACTIONS = "#B644B2";
const DISLIKE_ACTIONS = "#363636";
const FLASH_ACTIONS = "#5028D7";

const PROFILE_ICON_COLORS = [
    '#E64579',
    '#fabc60',
    '#E77980',
    '#F3AD76',
    '#FAE3C3',];

export default {
    PRIMARY_COLOR,
    SECONDARY_COLOR,
    WHITE,
    LIGHT_GRAY,
    GRAY,
    DARK_GRAY,
    BLACK,
    ONLINE_STATUS,
    OFFLINE_STATUS,
    STAR_ACTIONS,
    LIKE_ACTIONS,
    DISLIKE_ACTIONS,
    FLASH_ACTIONS,
    PROFILE_ICON_COLORS
}